defaults:
  - train: train_aquila_7b
  - _self_

experiment:
  exp_name: aquila2
  exp_dir: ./outputs
  task:
    type: train
    backend: megatron
    entrypoint: ./flagscale/train/train_gpt.py
  runner:
    backend: torchrun
    nnodes: 1 
    nproc_per_node: 8 
  envs:
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
    CUDA_DEVICE_MAX_CONNECTIONS: 1
  auto_tuner:
    space:
      context_parallel_size: [1]
      expert_model_parallel_size: [1]
    control:
      max_time_per_task: 300
      train_iters: 3
     
    # memory_model:
      # gpu_memory: 40536

action: auto_tune

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra 
