defaults:
  - train: train_llava1.5.yaml
  - _self_

experiment:
  exp_name: llava1.5
  exp_dir: ./outputs
  task:
    type: train
    backend: megatron
    entrypoint: ./flagscale/train/train_llava.py
  runner:
    backend: torchrun
    nnodes: 1 
    nproc_per_node: 8
  envs:
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7 
    CUDA_DEVICE_MAX_CONNECTIONS: 1
    NVTE_APPLY_QK_LAYER_SCALING: 0

action: run 

hydra: 
  run:
    dir: ${experiment.exp_dir}/hydra 
